name: "cflint"
description: "testing mvn within gh actions"
inputs:
  # who-to-greet:
  #   description: "who to greet"
  #   required: true
  #   default: "World"
outputs:
  # time:
  #   description: "the time"
runs:
  using: "docker"
  image: "Dockerfile"
  # args:
  #   - ${{ inputs.who-to-greet }}
