name: "cflint"
description: "testing mvn within gh actions"
inputs:
  rules-directory:
    description: "where to find cflint rules (.cflintrc)"
    required: false
    default: "/"
  folder-to-lint:
    description: "Target directory for cflint"
    required: true
    default: "/error"
outputs:
  results:
    description: "lint result"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.rules-directory }}
