name: "cflint-action"
description: "testing mvn within gh actions"
inputs:
  folder-to-lint:
    description: "Target directory for cflint"
    required: true
    default: "/error"
outputs:
  results:
    description: "lint result"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.folder-to-lint }}
