name: "cflint-action"
description: "ColdFusion linting tool for your workflow"
branding:
  icon: "search"
  color: "green"
inputs:
  folder-to-lint:
    description: "Target directory for cflint"
    required: true
    default: "/error"
outputs:
  results:
    description: "lint result"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.folder-to-lint }}
