name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - '*'

  workflow_dispatch:

env:
  TEST_RUNNER_URI: /tests/run.cfm?reporter=text

jobs:

  cflint:
    name: CFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CFLint
        id: cflint
        uses: csperando/cflint-action@v1
        with:
          folder-to-lint: .

      - name: Email report
        run: |
          echo add this later
